import type { Metadata } from "next";
import { Montserrat, Playfair } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});
const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${playfair.variable}  antialiased`}>
        <Navbar></Navbar>
        <div className="min-h-[calc(100vh-140px)] md:pt-10 md:pb-16 pt-5 pb-8 bg-primary-bg ">
          {children}
      </div>
      </body>
    </html>
  );
}
